Repository bellshade/HTML-CSS, pull requests merged in 2021-10, with the labels that each got.

#6 Html basic
  HTML/HTMLFilePath/README.md
  HTML/HTMLIFrame/README.md
Labels: documentation, enhancement

#3 Perbaikan Tipo dan Format Markdown
  BASIC.md
  HTML/Definisi HTML/Definisi.md
  HTML/Definisi HTML/Struktur HTML.md
  Template/readme.md
Labels: enhancement

#15 add: HTML Text Formatting
  HTML/HTML Quotation/HTML Quotation.md
  HTML/HTML Text Formatting/HTML Text Formatting.md
Labels: documentation, enhancement

#17 add: HTML Lists
  HTML/HTML Lists/HTML Lists.md
  HTML/HTML Lists/img/custom-ol.png
  HTML/HTML Lists/img/custom-ul.png
  HTML/HTML Lists/img/default-ol.png
  HTML/HTML Lists/img/default-ul.png
  HTML/HTML Lists/img/dl.png
Labels: documentation, enhancement

#22 add: menambahkan materi mengenai HTML Forms
  HTML/HTMLForms/README.md
Labels: documentation, enhancement, good first issue

#36 add: CSS Box Sizing
  CSS/CSS Box Sizing/CSS Box Sizing.md
Labels: documentation, enhancement

#33 add: menambahkan materi html form element pada HTMLForms
  HTML/HTMLForms/README.md
Labels: documentation, enhancement

#30 add: CSS Colors
  CSS/CSS Colors/CSS Colors.md
Labels: documentation, enhancement

#26 add: menambahkan materi input type
  HTML/HTML Input Types/HTML Input Types.md
Labels: documentation, enhancement

#39 CSS Flexbox
  CSS/CSS Flexbox/CSS Flexbox.md
Labels: documentation, enhancement

#25 add: menambahkan dokumentasi css comments
  CSS/CSS Comments/CSS Comments.md
Labels: documentation, enhancement

#40 add: Materi Custom Properties
  CSS/CSS Custom Properties/CSS Custom Properties.md
Labels: documentation, enhancement

#42 add: menambahkan HTML Responsive
  HTML/HTML Responsive/GAMBAR-sebelum.png
  HTML/HTML Responsive/GAMBAR-sesudah.png
  HTML/HTML Responsive/HTML Responsive.md
Labels: documentation, enhancement

#49 add: materi tentang html basic
  HTML/HTMLBasic/html_basic.md
Labels: documentation, enhancement, add

#47 add: HTML Headings-2
  HTML/HTML Headings/HTML Headings-2.md
Labels: documentation, enhancement, add

#46 Updatenya HTML Semantic.md
  HTML/HTML Semantic/HTML Semantic.md
Labels: bug, documentation, enhancement

#45 Membuat folder CSS Variable
  CSS/CSS Variable/CSS Variable.md
Labels: documentation, enhancement

#51 Fix: Memperbarui akses cepat
  README.md
Labels: Fix

#52 add: HTML CSS
  HTML/HTMLCSS/HTML CSS.md
Labels: documentation, enhancement, add

#55 docs: menambahkan atribut method
  HTML/HTMLAttributes/HTMLAttributes.md
Labels: documentation, enhancement

#54 add: materi tentang html block & inline elemen
  HTML/HTML Block & Inline/block & Inline.md
Labels: documentation, enhancement, add

#60 add: menambahkan link website template
  Template/readme.md
Labels: documentation, enhancement, add

#205 feat: menambahkan automation bot
  .mergify.yml
Labels: documentation, enhancement
