Repository bellshade/HTML-CSS, pull requests merged in 2021-11, with the labels that each got.

#209 feat: update bot
  .mergify.yml
Labels: enhancement

#212 feat: White Blue Web Profile Template
  Template/White Blue Template/css/style.css
  Template/White Blue Template/img/hobby/coding.webp
  Template/White Blue Template/img/hobby/gaming-2.webp
  Template/White Blue Template/img/hobby/music.webp
  Template/White Blue Template/img/logo_template.png
  Template/White Blue Template/img/portfolio/findmyhobby.webp
  Template/White Blue Template/img/portfolio/gawedong.webp
  Template/White Blue Template/img/portfolio/ikasma3bdg.webp
  Template/White Blue Template/img/portfolio/openblog.webp
  Template/White Blue Template/img/portfolio/smarthomeui.webp
  Template/White Blue Template/img/portfolio/sound.webp
  Template/White Blue Template/img/portfolio/twiceapi.webp
  Template/White Blue Template/img/profile-3.webp
  Template/White Blue Template/index.html
  Template/White Blue Template/js/script.js
  Template/White Blue Template/vendor/bootstrap/js/bootstrap.min.js
  Template/White Blue Template/vendor/bootstrap/js/bootstrap.min.js.map
  Template/White Blue Template/vendor/jquery/jquery.easing.1.3.js
  Template/White Blue Template/vendor/jquery/jquery.js
  Template/White Blue Template/vendor/popper/popper.min.js
Labels: ready-to-merge, documentation, enhancement, html files, css files, request tim html untuk review, request tim html-css untuk review, sudah direview !

#210 add: menambah template portfolio responsive
  Template/Bee Templates/Responsive Portfolio/README.md
  Template/Bee Templates/Responsive Portfolio/asset/img/BeeCode.png
  Template/Bee Templates/Responsive Portfolio/asset/img/My Code.png
  Template/Bee Templates/Responsive Portfolio/dist/css/app.css
  Template/Bee Templates/Responsive Portfolio/dist/css/customize.css
  Template/Bee Templates/Responsive Portfolio/index.html
Labels: ready-to-merge, add, html files, css files, request HTML-CSS team untuk review, markdown files, request docs team untuk review, request tim html untuk review, request tim html-css untuk review, sudah direview !

#213 docs: memperbarui akses cepat dan tambah daftar isi
  README.md
Labels: documentation, enhancement, markdown files, request docs team untuk review

#218 docs: memperbarui readme
  README.md
Labels: documentation, enhancement, markdown files, request docs team untuk review

#216 HTML ID & Script
  CSS/030 CSS Pseudo Elements/README.md
  HTML/021 HTML Id/README.md
  HTML/021 HTML Id/img/cara-memberi-style-pada-id.png
  HTML/021 HTML Id/img/specifity-pada-id.png
  HTML/023 HTML Script/README.md
  HTML/023 HTML Script/img/contoh-script-1.png
  HTML/023 HTML Script/img/contoh-script-2.png
  HTML/023 HTML Script/script.html
Labels: ready-to-merge, documentation, enhancement, html files, markdown files, request docs team untuk review, request tim html untuk review, sudah direview !

#214 add: materi CSS Introduction
  CSS/000 CSS Introduction/README.md
Labels: documentation, enhancement, add, markdown files, request docs team untuk review

#221 025 Html head
  HTML/025 HTML Head/README.md
  HTML/025 HTML Head/img/favicon.png
  HTML/027 HTML Meta/README.md
  HTML/029 HTML Responsive/GAMBAR-sebelum.png
  HTML/029 HTML Responsive/GAMBAR-sesudah.png
  HTML/029 HTML Responsive/README.md
  HTML/030 HTML Computer Code/readme.md
  HTML/031 HTML Semantic/README.md
  HTML/032 HTML Entity/README.md
  HTML/035 HTML Forms/README.md
  HTML/036 HTML Input Types/README.md
  HTML/040 HTML Button/README.md
  HTML/042 HTML Data/README.md
  HTML/043 HTML Canvas/README.md
Labels: documentation, enhancement, markdown files, request docs team untuk review
