Repository bellshade/HTML-CSS, pull requests merged in 2022-10, with the labels that each got.

#249 feat: add opengraph into META section
  HTML/027 HTML Meta/README.md
Labels: ready-to-merge, enhancement, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#252 feat: Adding Emojis 034
  HTML/034 HTML Emojis/README.md
Labels: ready-to-merge, enhancement, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#254 fix: typo
  HTML/050 HTML Tags List/README.md
Labels: bug, ready-to-merge, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#258 docs: merapihkan dokumentasi html hyperlink
  HTML/014 HTML HyperLink/README.md
Labels: ready-to-merge, documentation, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#259 docs: menambahkan materi css icons
  CSS/021 CSS Icons/README.md
Labels: ready-to-merge, documentation, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#260 docs: menambahkan materi css google fonts
  CSS/020 CSS Google Fonts/README.MD
Labels: ready-to-merge, documentation, sudah direview !, HACKTOBERFEST-ACCEPTED

#246 add: nesting elemen HTML
  HTML/004 HTML Elements/README.md
Labels: Ok to merge, ready-to-merge, documentation, add, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#261 docs: menambah materi HTML Select
  HTML/038 HTML Select/README.md
Labels: ready-to-merge, documentation, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#263 docs: Membuat dokumentasi HTML Figure
  HTML/046 HTML Figure/README.md
  HTML/046 HTML Figure/contoh-gambar.png
  HTML/046 HTML Figure/index.html
  HTML/046 HTML Figure/kucing-oren.jpg
Labels: ready-to-merge, documentation, html files, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#265 add: menambahkan materi css animation
  CSS/058 CSS Animation/README.md
  CSS/058 CSS Animation/assets/css_animation.gif
  README.md
Labels: ready-to-merge, add, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#268 docs: 028 HTML Base
  HTML/028 HTML Base/README.md
Labels: ready-to-merge, documentation, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#266 docs: 033 HTML Symbols
  HTML/033 HTML Symbols/README.md
Labels: ready-to-merge, documentation, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED

#270 docs: 044 HTML SVG
  HTML/044 HTML SVG/README.md
  HTML/044 HTML SVG/html-icon.svg
  HTML/044 HTML SVG/img/circle.png
  HTML/044 HTML SVG/img/contoh-html-2.png
  HTML/044 HTML SVG/img/contoh-html.png
  HTML/044 HTML SVG/img/ellipse.png
  HTML/044 HTML SVG/img/line.png
  HTML/044 HTML SVG/img/rect.png
  HTML/044 HTML SVG/index.html
Labels: ready-to-merge, documentation, html files, markdown files, sudah direview !, HACKTOBERFEST-ACCEPTED
